In [34]:
import pandas as pd
df = pd.read_csv('house_master.csv',encoding = 'CP949')
df

조사연도  MD제공용_가구고유번호          가중값 수도권여부  가구주_성별코드  가구원수 노인가구여부 조손가구여부  \
0      2020      10000112  1531.602344    G1         1     3     G2     G2   
1      2020      10000132  1314.119926    G1         2     2     G2     G2   
2      2020      10000162  1098.806050    G1         2     1     G1     G2   
3      2020      10000182  1124.027871    G1         1     2     G2     G2   
4      2020      10000192  1098.806050    G1         2     1     G2     G2   
...     ...           ...          ...   ...       ...   ...    ...    ...   
18059  2020     993800291   601.643255    G2         1     3     G2     G2   
18060  2020     994800251   384.069810    G2         1     5     G2     G2   
18061  2020     994800261   359.114694    G2         1     5     G2     G2   
18062  2020     994800291   416.635211    G2         2     2     G2     G2   
18063  2020     995800261   769.826228    G2         1     5     G2     G2   

      한부모가구여부 다문화가구여부(2012년~)  ... 원리금상환_가계지출감소항목코드  부채상환가능시기코드  가구주_은퇴여부  \
0          G2              G2  ...              NaN         1.0         1   
1          G2              G2  ...              4.0         1.0         1   
2          G2              G2  ...              NaN         NaN         1   
3          G2              G2  ...              NaN         NaN         1   
4          G2              G2  ...              NaN         NaN         1   
...       ...             ...  ...              ...         ...       ...   
18059      G2              G2  ...              1.0         1.0         1   
18060      G2              G2  ...              1.0         1.0         1   
18061      G2              G2  ...              NaN         1.0         2   
18062      G2              G2  ...              NaN         NaN         1   
18063      G2              G2  ...              NaN         1.0         1   

      가구주_미은퇴_은퇴연령  가구주_미은퇴_최소생활비 가구주_미은퇴_적정생활비 가구주_미은퇴_노후준비상황코드  가구주_은퇴_은퇴연령  \
0             70.0          400.0         500.0              3.0          NaN   
1             70.0          500.0         700.0              3.0          NaN   
2             75.0          100.0         150.0              3.0          NaN   
3             70.0          200.0         250.0              4.0          NaN   
4             65.0          250.0         300.0              3.0          NaN   
...            ...            ...           ...              ...          ...   
18059         55.0          400.0         500.0              3.0          NaN   
18060         60.0          300.0         600.0              2.0          NaN   
18061          NaN            NaN           NaN              NaN         56.0   
18062         60.0          200.0         300.0              3.0          NaN   
18063         60.0          150.0         300.0              1.0          NaN   

      가구주_은퇴_적정생활비충당여부  가구주은퇴_생활비재원마련코드(2014년~)  
0                  NaN                      NaN  
1                  NaN                      NaN  
2                  NaN                      NaN  
3                  NaN                      NaN  
4                  NaN                      NaN  
...                ...                      ...  
18059              NaN                      NaN  
18060              NaN                      NaN  
18061              3.0                      2.0  
18062              NaN                      NaN  
18063              NaN                      NaN  

[18064 rows x 159 columns]

In [35]:
df
df['입주형태코드']

0        2
1        3
2        2
3        2
4        3
        ..
18059    3
18060    1
18061    1
18062    2
18063    1
Name: 입주형태코드, Length: 18064, dtype: int64

In [36]:
columns = ["조사연도","가구주_성별코드","노인가구여부","조손가구여부","한부모가구여부","다문화가구여부(2012년~)","가구주_만연령","가구주_교육정도_학력코드","가구주_혼인상태코드","경상소득(보완)","입주형태코드"]

In [37]:
df1 = df[columns]

In [38]:
df1

조사연도  가구주_성별코드 노인가구여부 조손가구여부 한부모가구여부 다문화가구여부(2012년~)  가구주_만연령  \
0      2020         1     G2     G2      G2              G2       34   
1      2020         2     G2     G2      G2              G2       45   
2      2020         2     G1     G2      G2              G2       73   
3      2020         1     G2     G2      G2              G2       58   
4      2020         2     G2     G2      G2              G2       27   
...     ...       ...    ...    ...     ...             ...      ...   
18059  2020         1     G2     G2      G2              G2       42   
18060  2020         1     G2     G2      G2              G2       49   
18061  2020         1     G2     G2      G2              G2       57   
18062  2020         2     G2     G2      G2              G2       53   
18063  2020         1     G2     G2      G2              G2       44   

       가구주_교육정도_학력코드  가구주_혼인상태코드  경상소득(보완)  입주형태코드  
0                  6           2      6593       2  
1                  8           2     17720       3  
2                  2           3       908       2  
3                  4           2      2748       2  
4                  4           1      1015       3  
...              ...         ...       ...     ...  
18059              6           2       179       3  
18060              6           2     15454       1  
18061              6           2     15098       1  
18062              7           4      9114       2  
18063              6           2      7857       1  

[18064 rows x 11 columns]

In [39]:
df1 = df1.rename(columns = {
    "조사연도":'year',"가구주_성별코드":"sex","노인가구여부":"elders","조손가구여부":"grandparent","한부모가구여부":"one_parent","다문화가구여부(2012년~)":"global","가구주_만연령":"age","가구주_교육정도_학력코드":"education","가구주_혼인상태코드":"marriage","경상소득(보완)":"income","입주형태코드":"house"
})

In [40]:
df1

year  sex elders grandparent one_parent global  age  education  \
0      2020    1     G2          G2         G2     G2   34          6   
1      2020    2     G2          G2         G2     G2   45          8   
2      2020    2     G1          G2         G2     G2   73          2   
3      2020    1     G2          G2         G2     G2   58          4   
4      2020    2     G2          G2         G2     G2   27          4   
...     ...  ...    ...         ...        ...    ...  ...        ...   
18059  2020    1     G2          G2         G2     G2   42          6   
18060  2020    1     G2          G2         G2     G2   49          6   
18061  2020    1     G2          G2         G2     G2   57          6   
18062  2020    2     G2          G2         G2     G2   53          7   
18063  2020    1     G2          G2         G2     G2   44          6   

       marriage  income  house  
0             2    6593      2  
1             2   17720      3  
2             3     908      2  
3             2    2748      2  
4             1    1015      3  
...         ...     ...    ...  
18059         2     179      3  
18060         2   15454      1  
18061         2   15098      1  
18062         4    9114      2  
18063         2    7857      1  

[18064 rows x 11 columns]

In [43]:
def edu(x):
    if x == 2:
        return 6
    elif x == 3:
        return 9
    elif x == 4:
        return 12
    elif x == 5:
        return 14
    elif x == 6:
        return 16
    elif x == 7:
        return 18
    elif x == 8:
        return 21
    else:
        return 0
df1['education'] = df1['education'].apply(edu)

In [44]:
df2 = df1.loc[(df1["income"]> 0) & df1['education']>0]
df2

year  sex elders grandparent one_parent global  age  education  \
1      2020    2     G2          G2         G2     G2   45         21   
27     2020    1     G2          G2         G2     G2   47         21   
29     2020    2     G2          G2         G2     G2   59          9   
35     2020    2     G2          G2         G2     G2   30         21   
39     2020    1     G2          G2         G2     G2   69          9   
...     ...  ...    ...         ...        ...    ...  ...        ...   
18043  2020    2     G1          G2         G2     G2   66          9   
18044  2020    1     G2          G2         G2     G2   62          9   
18048  2020    1     G2          G2         G2     G2   49         21   
18051  2020    1     G2          G2         G2     G2   65          9   
18056  2020    1     G2          G2         G2     G2   68          9   

       marriage  income  house  
1             2   17720      3  
27            2   16884      1  
29            2   13384      5  
35            1    5607      1  
39            2    1455      1  
...         ...     ...    ...  
18043         4    2130      1  
18044         2    6479      1  
18048         2   14422      1  
18051         2    3495      1  
18056         2    2356      1  

[2227 rows x 11 columns]

In [45]:
import numpy as np
df2['income_log'] = np.log(df2['income'])
df2['education_log'] = np.log(df2['education'])

C:\Users\gksal\AppData\Local\Temp/ipykernel_12192/1013528947.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['income_log'] = np.log(df2['income'])
C:\Users\gksal\AppData\Local\Temp/ipykernel_12192/1013528947.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['education_log'] = np.log(df2['education'])


In [46]:
df2

year  sex elders grandparent one_parent global  age  education  \
1      2020    2     G2          G2         G2     G2   45         21   
27     2020    1     G2          G2         G2     G2   47         21   
29     2020    2     G2          G2         G2     G2   59          9   
35     2020    2     G2          G2         G2     G2   30         21   
39     2020    1     G2          G2         G2     G2   69          9   
...     ...  ...    ...         ...        ...    ...  ...        ...   
18043  2020    2     G1          G2         G2     G2   66          9   
18044  2020    1     G2          G2         G2     G2   62          9   
18048  2020    1     G2          G2         G2     G2   49         21   
18051  2020    1     G2          G2         G2     G2   65          9   
18056  2020    1     G2          G2         G2     G2   68          9   

       marriage  income  house  income_log  education_log  
1             2   17720      3    9.782449       3.044522  
27            2   16884      1    9.734122       3.044522  
29            2   13384      5    9.501815       2.197225  
35            1    5607      1    8.631771       3.044522  
39            2    1455      1    7.282761       2.197225  
...         ...     ...    ...         ...            ...  
18043         4    2130      1    7.663877       2.197225  
18044         2    6479      1    8.776321       2.197225  
18048         2   14422      1    9.576510       3.044522  
18051         2    3495      1    8.159089       2.197225  
18056         2    2356      1    7.764721       2.197225  

[2227 rows x 13 columns]

In [47]:
sex_dummies = pd.get_dummies(df2['sex']).rename(columns=lambda x : 's' + str(x))
sex_dummies.tail()

s1  s2
18043   0   1
18044   1   0
18048   1   0
18051   1   0
18056   1   0

In [31]:
job_dummies = pd.get_dummies(df2['job']).rename(columns = lambda x : 'd' + str(x) )
job_dummies

KeyError: 'job'

In [69]:
marriage_dummies = pd.get_dummies(df2['marriage']).rename(columns=lambda x : 'm' + str(x))
marriage_dummies.tail()

m1  m2  m3  m4
18043   0   0   0   1
18044   0   1   0   0
18048   0   1   0   0
18051   0   1   0   0
18056   0   1   0   0

In [70]:
elders_dummies = pd.get_dummies(df2['elders']).rename(columns = lambda x : 'e' + str(x[1]))
elders_dummies

e1  e2
1       0   1
27      0   1
29      0   1
35      0   1
39      0   1
...    ..  ..
18043   1   0
18044   0   1
18048   0   1
18051   0   1
18056   0   1

[2227 rows x 2 columns]

In [71]:
one_parent_dummies = pd.get_dummies(df2['one_parent']).rename(columns = lambda x :'o' + str(x[1]))
one_parent_dummies.tail()

o1  o2
18043   0   1
18044   0   1
18048   0   1
18051   0   1
18056   0   1

In [73]:
global_dummies = pd.get_dummies(df2['global']).rename(columns = lambda x : 'g'+ str(x[1]))
global_dummies.tail()

g1  g2
18043   0   1
18044   0   1
18048   0   1
18051   0   1
18056   0   1

In [74]:
df3 = pd.concat([df2,sex_dummies,marriage_dummies,elders_dummies,one_parent_dummies,global_dummies],axis=1)
df3.tail(5)

year  sex elders grandparent one_parent global  age  education  \
18043  2020    2     G1          G2         G2     G2   66          9   
18044  2020    1     G2          G2         G2     G2   62          9   
18048  2020    1     G2          G2         G2     G2   49         21   
18051  2020    1     G2          G2         G2     G2   65          9   
18056  2020    1     G2          G2         G2     G2   68          9   

       marriage  income  ...  m1  m2  m3  m4  e1  e2  o1  o2  g1  g2  
18043         4    2130  ...   0   0   0   1   1   0   0   1   0   1  
18044         2    6479  ...   0   1   0   0   0   1   0   1   0   1  
18048         2   14422  ...   0   1   0   0   0   1   0   1   0   1  
18051         2    3495  ...   0   1   0   0   0   1   0   1   0   1  
18056         2    2356  ...   0   1   0   0   0   1   0   1   0   1  

[5 rows x 26 columns]

In [110]:
df3['age2'] = df1['age'] ** 2
df3['globals'] = df3['global']
df3['education_log'] = df2['education_log']
df3['education_log']

1        3.044522
27       3.044522
29       2.197225
35       3.044522
39       2.197225
           ...   
18043    2.197225
18044    2.197225
18048    3.044522
18051    2.197225
18056    2.197225
Name: education_log, Length: 2227, dtype: float64

In [76]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [121]:
edu_model = ols("income ~ education_log + age + age2 +s2+m2+m3+m4+e2+o2+g2",data=df3).fit()
print(edu_model.summary())

                            OLS Regression Results                            
Dep. Variable:                 income   R-squared:                       0.305
Model:                            OLS   Adj. R-squared:                  0.302
Method:                 Least Squares   F-statistic:                     97.33
Date:                Mon, 08 May 2023   Prob (F-statistic):          3.46e-167
Time:                        21:26:18   Log-Likelihood:                -22137.
No. Observations:                2227   AIC:                         4.430e+04
Df Residuals:                    2216   BIC:                         4.436e+04
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept     -2.335e+04   3542.342     -6.592

In [131]:
edu_model = ols("income ~ education + age + age2 +s2+m2+m3+m4+e2+o2+g2",data=df3).fit()
print(edu_model.summary())

                            OLS Regression Results                            
Dep. Variable:                 income   R-squared:                       0.305
Model:                            OLS   Adj. R-squared:                  0.302
Method:                 Least Squares   F-statistic:                     97.33
Date:                Mon, 08 May 2023   Prob (F-statistic):          3.46e-167
Time:                        21:27:24   Log-Likelihood:                -22137.
No. Observations:                2227   AIC:                         4.430e+04
Df Residuals:                    2216   BIC:                         4.436e+04
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -7664.8999   3122.163     -2.455      0.0

In [161]:
edu = df3[['education_log','age','age2','s2','m2','m3','m4','e2','o2','g2' ]]
X = edu.values # X : 교육연수
ones = np.ones(X.shape[0])
X_mat = np.column_stack((ones,X))
X_mat

array([[ 1.        ,  3.04452244, 45.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 1.        ,  3.04452244, 47.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 1.        ,  2.19722458, 59.        , ...,  1.        ,
         1.        ,  1.        ],
       ...,
       [ 1.        ,  3.04452244, 49.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 1.        ,  2.19722458, 65.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 1.        ,  2.19722458, 68.        , ...,  1.        ,
         1.        ,  1.        ]])

In [162]:
Y = df3['income'].values # Y : 소득
beta_hat = np.linalg.inv(X_mat.T.dot(X_mat)).dot(X_mat.T).dot(Y) # 243page  회귀계수 추정
beta_hat.round(4)


array([-2.33524876e+04,  1.00448701e+04,  1.05228900e+02, -1.39690000e+00,
       -8.15684400e+02,  4.20734070e+03,  3.47717020e+03,  2.14951260e+03,
        1.46072490e+03, -4.40540700e+02,  3.47951300e+02])

In [163]:
Y_fitted = X_mat @ beta_hat  # Y 추정량
e = Y-Y_fitted   # 잔차
n = len(e)
k = beta_hat.shape[0]  # 설명변수 개수
sigma_hat2 = (e.T @ e) / (n-k) # 오차항의 분산에 대한 추정량
sigma_hat2.round(2)

25343372.77

In [164]:
XtX_Inv = np.linalg.inv(X_mat.T@X_mat)
cov = sigma_hat2 * XtX_Inv
cov

array([[ 1.25481895e+07, -1.10012603e+06, -2.75292692e+05,
         2.04255284e+03, -1.54779331e+04,  1.43575488e+05,
         8.43898412e+04,  2.83394471e+04, -5.93796682e+04,
        -8.48009212e+05, -2.29420560e+05],
       [-1.10012603e+06,  2.60737864e+05,  1.58129802e+04,
        -1.02170841e+02,  2.66373317e+03, -4.27434343e+04,
        -2.76189250e+04, -1.15329515e+04,  1.03013057e+04,
         6.70226513e+03, -5.86691980e+04],
       [-2.75292692e+05,  1.58129802e+04,  8.47287578e+03,
        -6.60183759e+01, -1.32191151e+03, -1.05359848e+04,
        -9.02582749e+03, -1.04625999e+04, -4.60405365e+03,
        -2.96861423e+03, -9.34159991e+03],
       [ 2.04255284e+03, -1.02170841e+02, -6.60183759e+01,
         5.29796190e-01,  1.31355426e+01,  6.51959786e+01,
         5.18415525e+01,  7.35653041e+01,  6.16579738e+01,
         2.32632551e+01,  5.83221066e+01],
       [-1.54779331e+04,  2.66373317e+03, -1.32191151e+03,
         1.31355426e+01,  1.04391721e+05,  2.28459141e+04,
  

In [165]:
se = np.sqrt(cov)
se

C:\Users\gksal\AppData\Local\Temp/ipykernel_12192/342131091.py:1: RuntimeWarning: invalid value encountered in sqrt
  se = np.sqrt(cov)


array([[3.54234238e+03,            nan,            nan, 4.51946108e+01,
                   nan, 3.78913562e+02, 2.90499296e+02, 1.68343242e+02,
                   nan,            nan,            nan],
       [           nan, 5.10624974e+02, 1.25749673e+02,            nan,
        5.16113667e+01,            nan,            nan,            nan,
        1.01495348e+02, 8.18673631e+01,            nan],
       [           nan, 1.25749673e+02, 9.20482253e+01,            nan,
                   nan,            nan,            nan,            nan,
                   nan,            nan,            nan],
       [4.51946108e+01,            nan,            nan, 7.27870998e-01,
        3.62429890e+00, 8.07440268e+00, 7.20010781e+00, 8.57702187e+00,
        7.85225915e+00, 4.82319967e+00, 7.63689116e+00],
       [           nan, 5.16113667e+01,            nan, 3.62429890e+00,
        3.23097076e+02, 1.51148649e+02,            nan,            nan,
                   nan,            nan, 1.20807864e+

In [166]:
se1 = np.zeros(k)
se1[0,] = se[0,0]
se1[1,] = se[1,1]
se1

array([3542.34237833,  510.62497422,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ])

In [167]:
lb = beta_hat - 2 * se1
hb = beta_hat + 2 * se1
bound = np.column_stack((lb,hb)) # 95% 유의수준에서 신뢰구간
bound.round(2)

array([[-3.043717e+04, -1.626780e+04],
       [ 9.023620e+03,  1.106612e+04],
       [ 1.052300e+02,  1.052300e+02],
       [-1.400000e+00, -1.400000e+00],
       [-8.156800e+02, -8.156800e+02],
       [ 4.207340e+03,  4.207340e+03],
       [ 3.477170e+03,  3.477170e+03],
       [ 2.149510e+03,  2.149510e+03],
       [ 1.460720e+03,  1.460720e+03],
       [-4.405400e+02, -4.405400e+02],
       [ 3.479500e+02,  3.479500e+02]])

In [168]:
t = beta_hat / se1
t.round(3)

C:\Users\gksal\AppData\Local\Temp/ipykernel_12192/3447034210.py:1: RuntimeWarning: divide by zero encountered in true_divide
  t = beta_hat / se1


array([-6.592, 19.672,    inf,   -inf,   -inf,    inf,    inf,    inf,
          inf,   -inf,    inf])

In [169]:
from scipy import stats
df = len(e) - 2
p0 = np.zeros(k)
for i in range(k):
    if t[i] > 0:
        p0[i,] = (1-stats.t.cdf(t[i],df=df))*2
    else:
        p0[i,] = (stats.t.cdf(t[i],df=df))*2
p0

array([5.38818667e-11, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00])